name = "zola-basic-starter-template"
description = """
A minimal Zola theme to serve as a starter or template
with clear, concise, and self-contained demonstrations of core functionality

Focused on idiomatic usage of core Zola features and Tera template primitives,
this theme utilizes only the standard Zola templates:
index.html, section.html, page.html, taxonomy_list.html, and taxonomy_single.html.

Currently supports or demonstrates:
* Menu nav bar and breadcrumb navigation
* Menu nav sections set through `[extra]` metadata in `config.toml`
* Content sections and pages with arbitrary nesting
* Zero-config navigation through arbitrary content section structure
* Taxonomy list and single-term pages
* Minimal static CSS stylesheet

To Do:
* Nav bar support for taxonomies
* Pagination support
* 404 page

Not Planned:
* SCSS
* Search

---
Created by Franco Posa (franco @ [francoposa.io](https://francoposa.io))
"""
# An optional tags to allow quick search
tags = ["minimal", "starter", "template"]
license = "MIT"
homepage = "https://github.com/francoposa/zola-basic-starter-template"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Franco Posa"
homepage = "https://francoposa.io"
